stages:
  - build0
  - build1
  - build2
  - build3
  - build4
  - build5
jobs:
  include:
    - stage: build0
      script: ./travis-ci.py 0
    - stage: build1
      script: ./travis-ci.py 1
    - stage: build2
      script: ./travis-ci.py 2
    - stage: build3
      script: ./travis-ci.py 3
    - stage: build4
      script: ./travis-ci.py 4
    - stage: build5
      script: ./travis-ci.py 5
dist: bionic
language: cpp
cache:
   directories:
    - $HOME/.cache/bazel/
